// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5qf9qx2MdA6rxkvahUIjOl0hRWerBwXY',
    appId: '1:465520899025:web:21db1594d7d0b40c2926f0',
    messagingSenderId: '465520899025',
    projectId: 'mozambique-app',
    authDomain: 'mozambique-app.firebaseapp.com',
    storageBucket: 'mozambique-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ54n8nyv9in5k8-K-vPIY0W0Meo25MUc',
    appId: '1:465520899025:android:b01ce8b15cf74b342926f0',
    messagingSenderId: '465520899025',
    projectId: 'mozambique-app',
    storageBucket: 'mozambique-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEU60z7sXzxQH8KTxPsaHzuN2oDEYnW_0',
    appId: '1:465520899025:ios:b8f5ffa30553063d2926f0',
    messagingSenderId: '465520899025',
    projectId: 'mozambique-app',
    storageBucket: 'mozambique-app.firebasestorage.app',
    iosBundleId: 'com.example.mozambiqueApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEU60z7sXzxQH8KTxPsaHzuN2oDEYnW_0',
    appId: '1:465520899025:ios:b8f5ffa30553063d2926f0',
    messagingSenderId: '465520899025',
    projectId: 'mozambique-app',
    storageBucket: 'mozambique-app.firebasestorage.app',
    iosBundleId: 'com.example.mozambiqueApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5qf9qx2MdA6rxkvahUIjOl0hRWerBwXY',
    appId: '1:465520899025:web:a9f6da9f490e78a62926f0',
    messagingSenderId: '465520899025',
    projectId: 'mozambique-app',
    authDomain: 'mozambique-app.firebaseapp.com',
    storageBucket: 'mozambique-app.firebasestorage.app',
  );
}
